[package]
name = "polymarket-core"
version = "0.1.0"
edition = "2024"

[dependencies]
polymarket_client_sdk_v2 = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
rust_decimal = { workspace = true }
alloy-primitives = { workspace = true }
futures = { workspace = true }
tokio-tungstenite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
